version: '3'
services:
  calendar-db:
    container_name: postgres-alpine
    restart: always
    image: postgres:9.6.16-alpine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: 123456  # TODO - move to environment file
      POSTGRES_DATABASE: calendar
      LANG: ru_RU.utf8
    expose:
      - 5432
    ports:
      - 5432:5432
