// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventPBAlertBefore_BeforeType int32

const (
	EventPBAlertBefore_DAYS    EventPBAlertBefore_BeforeType = 0
	EventPBAlertBefore_HOURS   EventPBAlertBefore_BeforeType = 1
	EventPBAlertBefore_MINUTES EventPBAlertBefore_BeforeType = 2
)

var EventPBAlertBefore_BeforeType_name = map[int32]string{
	0: "DAYS",
	1: "HOURS",
	2: "MINUTES",
}

var EventPBAlertBefore_BeforeType_value = map[string]int32{
	"DAYS":    0,
	"HOURS":   1,
	"MINUTES": 2,
}

func (x EventPBAlertBefore_BeforeType) String() string {
	return proto.EnumName(EventPBAlertBefore_BeforeType_name, int32(x))
}

func (EventPBAlertBefore_BeforeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0, 0, 0}
}

type EventPB struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	OccursAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=occurs_at,json=occursAt,proto3" json:"occurs_at,omitempty"`
	Subject              string               `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string               `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Duration             uint32               `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Location             string               `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	User                 *UserPB              `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventPB) Reset()         { *m = EventPB{} }
func (m *EventPB) String() string { return proto.CompactTextString(m) }
func (*EventPB) ProtoMessage()    {}
func (*EventPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *EventPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPB.Unmarshal(m, b)
}
func (m *EventPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPB.Marshal(b, m, deterministic)
}
func (m *EventPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPB.Merge(m, src)
}
func (m *EventPB) XXX_Size() int {
	return xxx_messageInfo_EventPB.Size(m)
}
func (m *EventPB) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPB.DiscardUnknown(m)
}

var xxx_messageInfo_EventPB proto.InternalMessageInfo

func (m *EventPB) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventPB) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EventPB) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *EventPB) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *EventPB) GetOccursAt() *timestamp.Timestamp {
	if m != nil {
		return m.OccursAt
	}
	return nil
}

func (m *EventPB) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EventPB) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EventPB) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *EventPB) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *EventPB) GetUser() *UserPB {
	if m != nil {
		return m.User
	}
	return nil
}

type EventPBAlertBefore struct {
	Type                 EventPBAlertBefore_BeforeType `protobuf:"varint,1,opt,name=type,proto3,enum=calendar.EventPBAlertBefore_BeforeType" json:"type,omitempty"`
	Before               uint32                        `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EventPBAlertBefore) Reset()         { *m = EventPBAlertBefore{} }
func (m *EventPBAlertBefore) String() string { return proto.CompactTextString(m) }
func (*EventPBAlertBefore) ProtoMessage()    {}
func (*EventPBAlertBefore) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0, 0}
}

func (m *EventPBAlertBefore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPBAlertBefore.Unmarshal(m, b)
}
func (m *EventPBAlertBefore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPBAlertBefore.Marshal(b, m, deterministic)
}
func (m *EventPBAlertBefore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPBAlertBefore.Merge(m, src)
}
func (m *EventPBAlertBefore) XXX_Size() int {
	return xxx_messageInfo_EventPBAlertBefore.Size(m)
}
func (m *EventPBAlertBefore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPBAlertBefore.DiscardUnknown(m)
}

var xxx_messageInfo_EventPBAlertBefore proto.InternalMessageInfo

func (m *EventPBAlertBefore) GetType() EventPBAlertBefore_BeforeType {
	if m != nil {
		return m.Type
	}
	return EventPBAlertBefore_DAYS
}

func (m *EventPBAlertBefore) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

type UserPB struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                []string             `protobuf:"bytes,3,rep,name=email,proto3" json:"email,omitempty"`
	Mobile               []string             `protobuf:"bytes,4,rep,name=mobile,proto3" json:"mobile,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserPB) Reset()         { *m = UserPB{} }
func (m *UserPB) String() string { return proto.CompactTextString(m) }
func (*UserPB) ProtoMessage()    {}
func (*UserPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *UserPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPB.Unmarshal(m, b)
}
func (m *UserPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPB.Marshal(b, m, deterministic)
}
func (m *UserPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPB.Merge(m, src)
}
func (m *UserPB) XXX_Size() int {
	return xxx_messageInfo_UserPB.Size(m)
}
func (m *UserPB) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPB.DiscardUnknown(m)
}

var xxx_messageInfo_UserPB proto.InternalMessageInfo

func (m *UserPB) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserPB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserPB) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *UserPB) GetMobile() []string {
	if m != nil {
		return m.Mobile
	}
	return nil
}

func (m *UserPB) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func init() {
	proto.RegisterEnum("calendar.EventPBAlertBefore_BeforeType", EventPBAlertBefore_BeforeType_name, EventPBAlertBefore_BeforeType_value)
	proto.RegisterType((*EventPB)(nil), "calendar.EventPB")
	proto.RegisterType((*EventPBAlertBefore)(nil), "calendar.EventPB.alertBefore")
	proto.RegisterType((*UserPB)(nil), "calendar.UserPB")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0xeb, 0xc4, 0xf1, 0xcf, 0x0d, 0x09, 0x46, 0x94, 0x62, 0xbc, 0x69, 0x09, 0x5d, 0x64,
	0xa5, 0x40, 0x0a, 0x2d, 0x85, 0x6e, 0x12, 0x1a, 0x68, 0x17, 0x6d, 0x83, 0x93, 0x2c, 0xba, 0x2a,
	0xb2, 0xa5, 0xa4, 0x2e, 0xb6, 0x65, 0x64, 0xb9, 0x90, 0xd7, 0x98, 0x79, 0x86, 0x79, 0xcf, 0x91,
	0x25, 0x3b, 0x19, 0x98, 0x45, 0x66, 0x15, 0x9d, 0x73, 0xcf, 0xa7, 0x88, 0x7b, 0x0c, 0xd3, 0x94,
	0xe4, 0xac, 0xa4, 0x44, 0xe0, 0x4a, 0x70, 0xc9, 0x91, 0xd7, 0xeb, 0xe8, 0xed, 0x89, 0xf3, 0x53,
	0xce, 0x16, 0xda, 0x4f, 0x9a, 0xe3, 0x42, 0x66, 0x05, 0xab, 0x25, 0x29, 0x2a, 0x13, 0x9d, 0x3d,
	0xd8, 0xe0, 0x6e, 0xfe, 0xb3, 0x52, 0x6e, 0xd7, 0x68, 0x0a, 0x83, 0x8c, 0x86, 0xd6, 0x3b, 0x6b,
	0x3e, 0x89, 0xd5, 0x09, 0x7d, 0x06, 0x48, 0x05, 0x23, 0x92, 0xd1, 0x3f, 0x44, 0x86, 0x03, 0xe5,
	0x8f, 0x97, 0x11, 0x36, 0x37, 0xe2, 0xfe, 0x46, 0xbc, 0xef, 0x6f, 0x8c, 0xfd, 0x2e, 0xbd, 0x92,
	0x2d, 0xda, 0x54, 0xb4, 0x47, 0x87, 0xb7, 0xd1, 0x2e, 0x6d, 0x50, 0xca, 0x72, 0xd6, 0xa1, 0xf6,
	0x6d, 0xb4, 0x4b, 0x2b, 0xf4, 0x13, 0xf8, 0x3c, 0x4d, 0x1b, 0x51, 0xb7, 0xe4, 0xe8, 0x26, 0xe9,
	0x99, 0xb0, 0x02, 0x43, 0x70, 0xeb, 0x26, 0xf9, 0xc7, 0x52, 0x19, 0x3a, 0x0a, 0xf3, 0xe3, 0x5e,
	0x22, 0x04, 0x76, 0xc2, 0xe9, 0x39, 0x74, 0xb5, 0xad, 0xcf, 0x28, 0x02, 0x8f, 0x36, 0x82, 0xc8,
	0x8c, 0x97, 0xa1, 0xa7, 0xb7, 0x75, 0xd1, 0xed, 0x2c, 0xe7, 0xa9, 0x99, 0xf9, 0x9a, 0xb9, 0x68,
	0xf4, 0x1e, 0xec, 0xa6, 0x66, 0x22, 0x04, 0xfd, 0xb2, 0x00, 0x5f, 0x5a, 0x3b, 0x28, 0x77, 0xbb,
	0x8e, 0xf5, 0x34, 0xba, 0xb7, 0x60, 0xac, 0x06, 0x42, 0xae, 0xd9, 0x91, 0x0b, 0x86, 0xbe, 0x80,
	0x2d, 0xcf, 0x15, 0xd3, 0xbd, 0x4c, 0x97, 0xf3, 0x2b, 0xd5, 0xd5, 0x86, 0x9f, 0x84, 0xb1, 0xf9,
	0xd9, 0xab, 0x7c, 0xac, 0x29, 0xf4, 0x06, 0x9c, 0x44, 0x7b, 0xba, 0xbf, 0x49, 0xdc, 0xa9, 0x19,
	0x06, 0xb8, 0x66, 0x91, 0x07, 0xf6, 0xd7, 0xd5, 0xef, 0x5d, 0xf0, 0x0a, 0xf9, 0x30, 0xfa, 0xf6,
	0xeb, 0x10, 0xef, 0x02, 0x0b, 0x8d, 0xc1, 0xfd, 0xf1, 0xfd, 0xe7, 0x61, 0xbf, 0xd9, 0x05, 0x83,
	0xd9, 0x9d, 0x05, 0x8e, 0x79, 0xe6, 0xb3, 0xcf, 0x44, 0xad, 0xa8, 0x24, 0x85, 0xf9, 0x03, 0xb5,
	0xa2, 0xf6, 0x8c, 0x5e, 0xc3, 0x88, 0x15, 0x24, 0xcb, 0x55, 0xf5, 0x43, 0x65, 0x1a, 0xd1, 0x3e,
	0xa6, 0xe0, 0x49, 0x96, 0x33, 0x55, 0x6b, 0x6b, 0x77, 0x0a, 0x7d, 0x04, 0x2f, 0xc9, 0x84, 0xfc,
	0x4b, 0xc9, 0xf9, 0x25, 0xb5, 0xf5, 0xd9, 0xc4, 0xd1, 0xd3, 0x0f, 0x8f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x4d, 0x15, 0x1e, 0x00, 0x03, 0x00, 0x00,
}
