// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventAlertBefore_BeforeType int32

const (
	EventAlertBefore_DAYS    EventAlertBefore_BeforeType = 0
	EventAlertBefore_HOURS   EventAlertBefore_BeforeType = 1
	EventAlertBefore_MINUTES EventAlertBefore_BeforeType = 2
)

var EventAlertBefore_BeforeType_name = map[int32]string{
	0: "DAYS",
	1: "HOURS",
	2: "MINUTES",
}

var EventAlertBefore_BeforeType_value = map[string]int32{
	"DAYS":    0,
	"HOURS":   1,
	"MINUTES": 2,
}

func (x EventAlertBefore_BeforeType) String() string {
	return proto.EnumName(EventAlertBefore_BeforeType_name, int32(x))
}

func (EventAlertBefore_BeforeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0, 0}
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	OccursAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=occurs_at,json=occursAt,proto3" json:"occurs_at,omitempty"`
	Subject              string               `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string               `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Duration             int64                `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Location             string               `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	User                 *User                `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Event) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Event) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Event) GetOccursAt() *timestamp.Timestamp {
	if m != nil {
		return m.OccursAt
	}
	return nil
}

func (m *Event) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Event) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Event) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Event) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type EventAlertBefore struct {
	Type                 EventAlertBefore_BeforeType `protobuf:"varint,1,opt,name=type,proto3,enum=api.EventAlertBefore_BeforeType" json:"type,omitempty"`
	Before               int64                       `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EventAlertBefore) Reset()         { *m = EventAlertBefore{} }
func (m *EventAlertBefore) String() string { return proto.CompactTextString(m) }
func (*EventAlertBefore) ProtoMessage()    {}
func (*EventAlertBefore) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

func (m *EventAlertBefore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAlertBefore.Unmarshal(m, b)
}
func (m *EventAlertBefore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAlertBefore.Marshal(b, m, deterministic)
}
func (m *EventAlertBefore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAlertBefore.Merge(m, src)
}
func (m *EventAlertBefore) XXX_Size() int {
	return xxx_messageInfo_EventAlertBefore.Size(m)
}
func (m *EventAlertBefore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAlertBefore.DiscardUnknown(m)
}

var xxx_messageInfo_EventAlertBefore proto.InternalMessageInfo

func (m *EventAlertBefore) GetType() EventAlertBefore_BeforeType {
	if m != nil {
		return m.Type
	}
	return EventAlertBefore_DAYS
}

func (m *EventAlertBefore) GetBefore() int64 {
	if m != nil {
		return m.Before
	}
	return 0
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                []string             `protobuf:"bytes,3,rep,name=email,proto3" json:"email,omitempty"`
	Mobile               []string             `protobuf:"bytes,4,rep,name=mobile,proto3" json:"mobile,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetMobile() []string {
	if m != nil {
		return m.Mobile
	}
	return nil
}

func (m *User) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.EventAlertBefore_BeforeType", EventAlertBefore_BeforeType_name, EventAlertBefore_BeforeType_value)
	proto.RegisterType((*Event)(nil), "api.Event")
	proto.RegisterType((*EventAlertBefore)(nil), "api.Event.alertBefore")
	proto.RegisterType((*User)(nil), "api.User")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x34, 0x49, 0x9b, 0xdc, 0x42, 0x29, 0xc3, 0x87, 0x84, 0x80, 0xa8, 0x5d, 0xb9,
	0x9a, 0x42, 0x45, 0xc5, 0x65, 0xc5, 0x82, 0x2e, 0x54, 0x48, 0xdb, 0x85, 0x2b, 0x99, 0x24, 0xd3,
	0x1a, 0x49, 0x3a, 0x61, 0x32, 0x11, 0xfa, 0x0e, 0x2e, 0xdc, 0xf8, 0xbe, 0xce, 0x9f, 0xa4, 0x0a,
	0x2e, 0xea, 0xaa, 0xf7, 0x9c, 0x39, 0xbf, 0xcb, 0x74, 0x4e, 0xc0, 0x27, 0x65, 0x86, 0x4b, 0xce,
	0x04, 0x43, 0xb6, 0x1c, 0xc3, 0xa3, 0x35, 0x63, 0xeb, 0x9c, 0x8e, 0xb5, 0x15, 0xd7, 0xab, 0xb1,
	0xc8, 0x0a, 0x5a, 0x09, 0x52, 0x94, 0x26, 0x35, 0xfa, 0x74, 0xc0, 0x9d, 0xbd, 0xd1, 0x8d, 0x40,
	0x03, 0xe8, 0x64, 0x69, 0x60, 0x1d, 0x5b, 0xa7, 0x7e, 0x24, 0x27, 0x74, 0x05, 0x90, 0x70, 0x4a,
	0x04, 0x4d, 0x9f, 0x89, 0x08, 0x3a, 0xd2, 0xef, 0x4f, 0x42, 0x6c, 0xf6, 0xe1, 0x76, 0x1f, 0x5e,
	0xb4, 0xfb, 0x22, 0xbf, 0x49, 0x4f, 0x85, 0x42, 0xeb, 0x32, 0x6d, 0x51, 0x7b, 0x3f, 0xda, 0xa4,
	0x0d, 0x9a, 0xd2, 0x9c, 0x36, 0xa8, 0xb3, 0x1f, 0x6d, 0xd2, 0x12, 0xbd, 0x04, 0x9f, 0x25, 0x49,
	0xcd, 0x2b, 0x45, 0xba, 0x7b, 0x49, 0xcf, 0x84, 0x25, 0x18, 0x40, 0xaf, 0xaa, 0xe3, 0x57, 0x9a,
	0x88, 0xa0, 0xab, 0xff, 0x7e, 0x2b, 0x11, 0x02, 0x27, 0x66, 0xe9, 0x36, 0xe8, 0x69, 0x5b, 0xcf,
	0x28, 0x04, 0x2f, 0xad, 0x39, 0x11, 0x19, 0xdb, 0x04, 0x9e, 0xf4, 0xed, 0x68, 0xa7, 0xd5, 0x59,
	0xce, 0x12, 0x73, 0xe6, 0x6b, 0x66, 0xa7, 0xd1, 0x21, 0x38, 0x75, 0x45, 0x79, 0x00, 0xfa, 0x66,
	0x3e, 0x56, 0x4d, 0x2d, 0xa5, 0x11, 0x69, 0x3b, 0x7c, 0xb7, 0xa0, 0x4f, 0x72, 0xca, 0xc5, 0x35,
	0x5d, 0x31, 0x4e, 0xd1, 0x39, 0x38, 0x62, 0x5b, 0x52, 0x5d, 0xc8, 0x60, 0x72, 0xa2, 0xe3, 0xba,
	0x28, 0xfc, 0x23, 0x85, 0xcd, 0xcf, 0x42, 0x06, 0x23, 0x1d, 0x47, 0x07, 0xd0, 0x8d, 0xb5, 0xa7,
	0x1b, 0xb3, 0xa3, 0x46, 0x8d, 0x30, 0xc0, 0x77, 0x16, 0x79, 0xe0, 0xdc, 0x4c, 0x9f, 0xe6, 0xc3,
	0x7f, 0xc8, 0x07, 0xf7, 0xf6, 0x71, 0x19, 0xcd, 0x87, 0x16, 0xea, 0x43, 0xef, 0xfe, 0xee, 0x61,
	0xb9, 0x98, 0xcd, 0x87, 0x9d, 0xd1, 0x87, 0x05, 0x8e, 0xba, 0xdd, 0xaf, 0xcf, 0x42, 0x3e, 0xc9,
	0x86, 0x14, 0x66, 0xbd, 0x7c, 0x12, 0x35, 0xa3, 0xff, 0xe0, 0xd2, 0x82, 0x64, 0xb9, 0xac, 0xda,
	0x96, 0xa6, 0x11, 0xea, 0x2a, 0x05, 0x8b, 0xb3, 0x9c, 0xca, 0x1a, 0x95, 0xdd, 0x28, 0x74, 0x01,
	0x5e, 0x9c, 0x71, 0xf1, 0x92, 0x92, 0xed, 0x5f, 0x6a, 0x6a, 0xb3, 0x71, 0x57, 0x9f, 0x9e, 0x7d,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x66, 0xff, 0x6c, 0xd6, 0xe4, 0x02, 0x00, 0x00,
}
